namespace Dolo.PlanetAI.Websocket.Enum;

internal enum Protocol
{
	PING = 500,
	PONG = 501,
	CONNECTION_ABNORMAL_CLOSED = 510,
	CONNECTION_CLOSED = 511,
	CONNECTION_FAILED = 512,
	CONNECTION_OPENED = 513,
	AUTHENTICATE_REQUEST = 10,
	AUTHENTICATE_RESPONSE = 11,
	DISCONNECT = 12
}
